#!/usr/bin/env python3
"""Regenerate docs/05-traceability.md and fail on any coverage gap.

Requirement-to-test coverage comes from the hand-authored map in
docs/06-verification-map.md, NOT from task membership. Deriving it from tasks
credited every test of a task to every requirement of that task, which let a
requirement report coverage with no test that would fail if it broke.

Sources:
  docs/01-requirements.md    defines FR-/NFR- ids
  docs/03-tasks.md           defines tasks, their traced requirements, their tests
  docs/04-test-strategy.md   defines TC-/MW- ids
  docs/06-verification-map.md  the authored requirement -> test claim

Run: python scripts/traceability.py   (exit code 1 on any gap)
"""
import re, sys, collections, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
req = (root / "docs/01-requirements.md").read_text()
tasks = (root / "docs/03-tasks.md").read_text()
tests = (root / "docs/04-test-strategy.md").read_text()
vmap_src = (root / "docs/06-verification-map.md").read_text()

reqs = sorted(set(re.findall(r"\*\*((?:FR|NFR)-\d+)\*\*", req)))
tcs = sorted(set(re.findall(r"^\| (TC-\d+) \|", tests, re.M)))
mws = sorted(set(re.findall(r"^\| (MW-\d+) \|", tests, re.M)))
known_tests = set(tcs) | set(mws)

# --- authored requirement -> test map -------------------------------------
vmap = {}
for line in vmap_src.splitlines():
    m = re.match(r"^\|\s*((?:FR|NFR)-\d+)\s*\|\s*([^|]*?)\s*\|\s*$", line)
    if m:
        vmap[m.group(1)] = re.findall(r"(?:TC|MW)-\d+", m.group(2))

# --- tasks ----------------------------------------------------------------
blocks = re.findall(
    r"### (TASK-\d+) ([^\n]+)\n\*\*Traces\*\* ([^\n]+)\n.*?\*\*Verified by\*\* ([^\n]+)",
    tasks, re.S)

req2task = collections.defaultdict(list)
rows = []
for tid, name, tr, vb in blocks:
    trs = re.findall(r"(?:FR|NFR)-\d+", tr)
    vbs = mws if re.search(r"MW-01 to MW-\d+", vb) else re.findall(r"(?:TC|MW)-\d+", vb)
    rows.append((tid, name.strip(), trs, vbs))
    for r in trs:
        req2task[r].append(tid)

task_tests = set()
for _, _, _, vbs in rows:
    task_tests |= set(vbs)

errors = []
for r in reqs:
    if not req2task[r]:
        errors.append(f"{r} is implemented by no task")
    if r not in vmap:
        errors.append(f"{r} has no row in docs/06-verification-map.md")
    elif not vmap[r]:
        errors.append(f"{r} has an empty verification row")
    else:
        for t in vmap[r]:
            if t not in known_tests:
                errors.append(f"{r} claims undefined test {t}")
        # a requirement's tests must actually be scheduled by some task
        unscheduled = [t for t in vmap[r] if t not in task_tests]
        if unscheduled:
            errors.append(
                f"{r} is verified by {', '.join(unscheduled)}, which no task builds")

for r in sorted(set(vmap) - set(reqs)):
    errors.append(f"{r} has a verification row but is not defined in 01-requirements.md")
for r in sorted(set(req2task) - set(reqs)):
    errors.append(f"{r} is traced by a task but not defined in 01-requirements.md")
for tid, _, _, vbs in rows:
    for v in vbs:
        if v not in known_tests:
            errors.append(f"{tid} references undefined test {v}")
for t in tcs + mws:
    if t not in task_tests:
        errors.append(f"{t} is built by no task")
    if not any(t in v for v in vmap.values()):
        errors.append(f"{t} verifies no requirement")

# --- emit -----------------------------------------------------------------
out = [
    "# Interview CoPilot — Traceability Matrix", "",
    "Version 1.1. Generated by `python scripts/traceability.py`. Do not edit by hand.", "",
    "Requirement-to-test coverage is read from the hand-authored",
    "`06-verification-map.md`, not inferred from task membership. The earlier",
    "inference credited every test of a task to every requirement of that task,",
    "so a requirement could report coverage with no test that would fail if it",
    "broke. The script exits non-zero on any gap, so CI fails when the documents",
    "drift.", "",
    f"Coverage: {len(reqs)} requirements, {len(rows)} tasks, "
    f"{len(tcs)} automated test cases, {len(mws)} manual checks.", "",
    "## Requirement to task to test", "",
    "| Requirement | Built by | Verified by |", "|---|---|---|",
]
for r in reqs:
    out.append(f"| {r} | {', '.join(sorted(set(req2task[r]))) or '**GAP**'} | "
               f"{', '.join(vmap.get(r, [])) or '**GAP**'} |")
out += ["", "## Task to requirement to test", "",
        "| Task | Name | Traces | Builds tests |", "|---|---|---|---|"]
for tid, name, trs, vbs in rows:
    out.append(f"| {tid} | {name} | {', '.join(trs)} | {', '.join(vbs)} |")
(root / "docs/05-traceability.md").write_text("\n".join(out) + "\n")

if errors:
    print("TRACEABILITY GAPS:", file=sys.stderr)
    for e in errors:
        print("  -", e, file=sys.stderr)
    sys.exit(1)
print(f"Traceability OK: {len(reqs)} requirements, {len(rows)} tasks, "
      f"{len(tcs)} test cases, {len(mws)} manual checks. "
      f"Every requirement has an authored verification row.")
