#!/usr/bin/env python3
"""Regenerate docs/05-traceability.md and fail on any coverage gap.

Sources: docs/01-requirements.md, docs/03-tasks.md, docs/04-test-strategy.md.
Run: python scripts/traceability.py  (exit code 1 on a gap)
"""
import re, sys, collections, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
req = (root / "docs/01-requirements.md").read_text()
tasks = (root / "docs/03-tasks.md").read_text()
tests = (root / "docs/04-test-strategy.md").read_text()

reqs = sorted(set(re.findall(r"\*\*((?:FR|NFR)-\d+)\*\*", req)))
tcs = sorted(set(re.findall(r"^\| (TC-\d+) \|", tests, re.M)))
mws = sorted(set(re.findall(r"^\| (MW-\d+) \|", tests, re.M)))

blocks = re.findall(
    r"### (TASK-\d+) ([^\n]+)\n\*\*Traces\*\* ([^\n]+)\n.*?\*\*Verified by\*\* ([^\n]+)",
    tasks, re.S)

req2task = collections.defaultdict(list)
req2tc = collections.defaultdict(list)
rows = []
for tid, name, tr, vb in blocks:
    trs = re.findall(r"(?:FR|NFR)-\d+", tr)
    vbs = mws if "MW-01 to MW-10" in vb else re.findall(r"(?:TC|MW)-\d+", vb)
    rows.append((tid, name.strip(), trs, vbs))
    for r in trs:
        req2task[r].append(tid)
        req2tc[r] += vbs

errors = []
for r in reqs:
    if not req2task[r]:
        errors.append(f"{r} has no task")
    if not req2tc[r]:
        errors.append(f"{r} has no test")
for r in sorted(set(req2task) - set(reqs)):
    errors.append(f"{r} is traced by a task but not defined in 01-requirements.md")
known = set(tcs) | set(mws)
for tid, _, _, vbs in rows:
    for v in vbs:
        if v not in known:
            errors.append(f"{tid} references undefined test {v}")
for t in tcs + mws:
    if not any(t in vbs for _, _, _, vbs in rows):
        errors.append(f"{t} is not referenced by any task")

out = [
    "# Interview CoPilot — Traceability Matrix", "",
    "Version 1.0. Generated by `python scripts/traceability.py` from",
    "`01-requirements.md`, `03-tasks.md` and `04-test-strategy.md`. Do not edit by hand.",
    "The script exits non-zero on any gap, so CI fails when the documents drift.", "",
    f"Coverage: {len(reqs)} requirements, {len(rows)} tasks, "
    f"{len(tcs)} automated test cases, {len(mws)} manual checks.", "",
    "## Requirement to task to test", "",
    "| Requirement | Tasks | Verified by |", "|---|---|---|",
]
for r in reqs:
    out.append(f"| {r} | {', '.join(sorted(set(req2task[r]))) or '**GAP**'} | "
               f"{', '.join(sorted(set(req2tc[r]))) or '**GAP**'} |")
out += ["", "## Task to requirement to test", "",
        "| Task | Name | Traces | Verified by |", "|---|---|---|---|"]
for tid, name, trs, vbs in rows:
    out.append(f"| {tid} | {name} | {', '.join(trs)} | {', '.join(vbs)} |")
(root / "docs/05-traceability.md").write_text("\n".join(out) + "\n")

if errors:
    print("TRACEABILITY GAPS:", file=sys.stderr)
    for e in errors:
        print("  -", e, file=sys.stderr)
    sys.exit(1)
print(f"Traceability OK: {len(reqs)} requirements, {len(rows)} tasks, "
      f"{len(tcs)} test cases, {len(mws)} manual checks.")
